# Generated by Django 3.1.5 on 2021-02-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='initaited_by',
            new_name='initiated_by',
        ),
    ]
