# Generated by Django 3.1.5 on 2021-01-10 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('occupations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='occupation',
            new_name='Specialization',
        ),
        migrations.AddField(
            model_name='occupation',
            name='Skills',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
