# Generated by Django 3.1.5 on 2021-01-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiringInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('Required_for', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('estimated_duration', models.FloatField()),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
