# Generated by Django 3.1.5 on 2021-01-26 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(help_text='Your Full name', max_length=200)),
                ('address', models.CharField(help_text='address must be valid and genuine', max_length=50)),
                ('date', models.DateField(help_text='Date for the reservation')),
                ('Required_for', models.CharField(help_text='Must be the area in which he/she is expert in', max_length=100)),
                ('description', models.TextField(help_text='Full description of the work')),
                ('estimated_duration', models.FloatField(help_text='For how many hour do you need him/her')),
                ('contact_no', models.CharField(help_text='Contact no of yours', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('RE', 'Recruiter'), ('AFNR', 'Agriculture,Food and Natural Resources'), ('A/C', 'Architecture and Construction'), ('Technology', 'Arts, Technology and Communications'), ('BMA', 'Business Management and Administration'), ('EDU', 'Education and Training'), ('FIN', 'Finance'), ('GOV', 'Government and Public Administration'), ('HS', 'Health Science'), ('HT', 'Hospitality and Tourism'), ('Humanservice', 'Human Service'), ('IT', 'Information Technology'), ('LAW', 'Law and Pulblic Safety'), ('Manufacture', 'Manufacturing'), ('sales', 'Sales and Marketing'), ('Eng/math', 'Engineering and Mathematics'), ('Trans', 'Transportation')], max_length=25)),
                ('estimated_time', models.IntegerField(help_text='required time to complete the job in hr')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
