# Generated by Django 3.1.5 on 2021-02-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hiring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanpowers',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='projectmanpowers',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectManpowers',
        ),
    ]
