# Generated by Django 3.1.5 on 2021-01-10 03:53

import User.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='allocates whether the user is staff or not', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Allocates whether is active or not unselect this in case of deleting acounts', verbose_name='active')),
                ('is_freelancer', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(blank=True, default='', help_text='gender of the user', max_length=10, null=True)),
                ('dob', models.CharField(blank=True, help_text='Date of birth of the user', max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, help_text='Nationality of the user', max_length=25, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', User.models.UserManager()),
            ],
        ),
    ]
