# Generated by Django 4.1.6 on 2023-02-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_hiring',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
