# Generated by Django 3.1.5 on 2021-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pay_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
