# Generated by Django 3.1.5 on 2021-01-10 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210110_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Skills',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Specialization',
            field=models.CharField(choices=[('RE', 'Recruiter'), ('AFNR', 'Agriculture,Food and Natural Resources'), ('A/C', 'Architecture and Construction'), ('Technology', 'Arts, Technology and Communications'), ('BMA', 'Business Management and Administration'), ('EDU', 'Education and Training'), ('FIN', 'Finance'), ('GOV', 'Government and Public Administration'), ('HS', 'Health Science'), ('HT', 'Hospitality and Tourism'), ('Humanservice', 'Human Service'), ('IT', 'Information Technology'), ('LAW', 'Law and Pulblic Safety'), ('Manufacture', 'Manufacturing'), ('sales', 'Sales and Marketing'), ('Eng/math', 'Engineering and Mathematics'), ('Trans', 'Transportation')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
